// AUTO-GENERATED by build-photos.js. Do not edit by hand; re-run the script instead.
const highlights = [
  {
    "src": "photos/highlight/I&A Haldi-46.jpg",
    "caption": "Haldi"
  },
  {
    "src": "photos/highlight/I&A Haldi-278.jpg",
    "caption": "Haldi"
  },
  {
    "src": "photos/highlight/I&A Sangeet-295.jpg",
    "caption": "Sangeet"
  },
  {
    "src": "photos/highlight/I&A Wedding & Reception-383.jpg",
    "caption": "Wedding & Reception"
  },
  {
    "src": "photos/highlight/I&A Wedding & Reception-640_websize.jpg",
    "caption": "Wedding & Reception-640_websize"
  },
  {
    "src": "photos/highlight/I&A Wedding & Reception-870.jpg",
    "caption": "Wedding & Reception"
  },
  {
    "src": "photos/highlight/I&A Wedding & Reception-874.jpg",
    "caption": "Wedding & Reception"
  }
];

const people = [
  {
    "id": "anushka",
    "name": "Anushka",
    "photos": [
      {
        "src": "photos/anushka/1TSK2912_websize.jpg",
        "caption": "1TSK2912_websize"
      },
      {
        "src": "photos/anushka/1TSK9873_websize.jpg",
        "caption": "1TSK9873_websize"
      },
      {
        "src": "photos/anushka/I&A Haldi-39.jpg",
        "caption": "Haldi"
      },
      {
        "src": "photos/anushka/I&A Haldi-40_websize.jpg",
        "caption": "Haldi-40_websize"
      },
      {
        "src": "photos/anushka/I&A Haldi-131_websize.jpg",
        "caption": "Haldi-131_websize"
      },
      {
        "src": "photos/anushka/I&A Sangeet-148_websize.jpg",
        "caption": "Sangeet-148_websize"
      },
      {
        "src": "photos/anushka/I&A Sangeet-151_websize.jpg",
        "caption": "Sangeet-151_websize"
      },
      {
        "src": "photos/anushka/I&A Sangeet-245.jpg",
        "caption": "Sangeet"
      },
      {
        "src": "photos/anushka/I&A Sangeet-251_websize.jpg",
        "caption": "Sangeet-251_websize"
      },
      {
        "src": "photos/anushka/I&A Sangeet-257_websize.jpg",
        "caption": "Sangeet-257_websize"
      },
      {
        "src": "photos/anushka/I&A Sangeet-296_websize.jpg",
        "caption": "Sangeet-296_websize"
      },
      {
        "src": "photos/anushka/I&A Sangeet-371.jpg",
        "caption": "Sangeet"
      },
      {
        "src": "photos/anushka/I&A Sangeet-373_websize.jpg",
        "caption": "Sangeet-373_websize"
      },
      {
        "src": "photos/anushka/I&A Wedding & Reception-260_websize.jpg",
        "caption": "Wedding & Reception-260_websize"
      },
      {
        "src": "photos/anushka/I&A Wedding & Reception-336_websize.jpg",
        "caption": "Wedding & Reception-336_websize"
      },
      {
        "src": "photos/anushka/I&A Wedding & Reception-474.jpg",
        "caption": "Wedding & Reception"
      },
      {
        "src": "photos/anushka/I&A Wedding & Reception-475.jpg",
        "caption": "Wedding & Reception"
      },
      {
        "src": "photos/anushka/I&A Wedding & Reception-476.jpg",
        "caption": "Wedding & Reception"
      },
      {
        "src": "photos/anushka/I&A Wedding & Reception-477.jpg",
        "caption": "Wedding & Reception"
      },
      {
        "src": "photos/anushka/I&A Wedding & Reception-478_websize.jpg",
        "caption": "Wedding & Reception-478_websize"
      },
      {
        "src": "photos/anushka/I&A Wedding & Reception-479_websize.jpg",
        "caption": "Wedding & Reception-479_websize"
      },
      {
        "src": "photos/anushka/I&A Wedding & Reception-576_websize.jpg",
        "caption": "Wedding & Reception-576_websize"
      }
    ]
  },
  {
    "id": "ayush",
    "name": "Ayush",
    "photos": [
      {
        "src": "photos/ayush/I&A Haldi-63_websize.jpg",
        "caption": "Haldi-63_websize"
      },
      {
        "src": "photos/ayush/I&A Haldi-218_websize.jpg",
        "caption": "Haldi-218_websize"
      },
      {
        "src": "photos/ayush/I&A Haldi-283_websize.jpg",
        "caption": "Haldi-283_websize"
      },
      {
        "src": "photos/ayush/I&A Haldi-292_websize.jpg",
        "caption": "Haldi-292_websize"
      },
      {
        "src": "photos/ayush/I&A Haldi-303_websize.jpg",
        "caption": "Haldi-303_websize"
      },
      {
        "src": "photos/ayush/I&A Sangeet-25_websize.jpg",
        "caption": "Sangeet-25_websize"
      },
      {
        "src": "photos/ayush/I&A Sangeet-30_websize.jpg",
        "caption": "Sangeet-30_websize"
      },
      {
        "src": "photos/ayush/I&A Wedding & Reception-27_websize.jpg",
        "caption": "Wedding & Reception-27_websize"
      },
      {
        "src": "photos/ayush/I&A Wedding & Reception-161_websize.jpg",
        "caption": "Wedding & Reception-161_websize"
      },
      {
        "src": "photos/ayush/I&A Wedding & Reception-323_websize.jpg",
        "caption": "Wedding & Reception-323_websize"
      },
      {
        "src": "photos/ayush/I&A Wedding & Reception-911_websize.jpg",
        "caption": "Wedding & Reception-911_websize"
      }
    ]
  },
  {
    "id": "couple",
    "name": "Couple",
    "photos": [
      {
        "src": "photos/couple/1TSK2424_websize.jpg",
        "caption": "1TSK2424_websize"
      },
      {
        "src": "photos/couple/1TSK2662_websize.jpg",
        "caption": "1TSK2662_websize"
      },
      {
        "src": "photos/couple/1TSK3673_websize.jpg",
        "caption": "1TSK3673_websize"
      },
      {
        "src": "photos/couple/1TSK3692_websize.jpg",
        "caption": "1TSK3692_websize"
      },
      {
        "src": "photos/couple/1TSK4102_websize.jpg",
        "caption": "1TSK4102_websize"
      },
      {
        "src": "photos/couple/1TSK5967_websize.jpg",
        "caption": "1TSK5967_websize"
      },
      {
        "src": "photos/couple/1TSK8434_websize.jpg",
        "caption": "1TSK8434_websize"
      },
      {
        "src": "photos/couple/I&A FIrst Look-86_websize.jpg",
        "caption": "FIrst Look-86_websize"
      },
      {
        "src": "photos/couple/I&A FIrst Look-98_websize.jpg",
        "caption": "FIrst Look-98_websize"
      },
      {
        "src": "photos/couple/I&A Haldi-59_websize.jpg",
        "caption": "Haldi-59_websize"
      },
      {
        "src": "photos/couple/I&A Haldi-68_websize.jpg",
        "caption": "Haldi-68_websize"
      },
      {
        "src": "photos/couple/I&A Haldi-77_websize.jpg",
        "caption": "Haldi-77_websize"
      },
      {
        "src": "photos/couple/I&A Haldi-164_websize.jpg",
        "caption": "Haldi-164_websize"
      },
      {
        "src": "photos/couple/I&A Haldi-466_websize.jpg",
        "caption": "Haldi-466_websize"
      },
      {
        "src": "photos/couple/I&A Haldi-524_websize.jpg",
        "caption": "Haldi-524_websize"
      },
      {
        "src": "photos/couple/I&A Sangeet-80_websize.jpg",
        "caption": "Sangeet-80_websize"
      },
      {
        "src": "photos/couple/I&A Sangeet-115_websize.jpg",
        "caption": "Sangeet-115_websize"
      },
      {
        "src": "photos/couple/I&A Sangeet-305_websize.jpg",
        "caption": "Sangeet-305_websize"
      },
      {
        "src": "photos/couple/I&A Wedding & Reception-333_websize.jpg",
        "caption": "Wedding & Reception-333_websize"
      },
      {
        "src": "photos/couple/I&A Wedding & Reception-370_websize.jpg",
        "caption": "Wedding & Reception-370_websize"
      },
      {
        "src": "photos/couple/I&A Wedding & Reception-503_websize.jpg",
        "caption": "Wedding & Reception-503_websize"
      },
      {
        "src": "photos/couple/I&A Wedding & Reception-589_websize.jpg",
        "caption": "Wedding & Reception-589_websize"
      },
      {
        "src": "photos/couple/I&A Wedding & Reception-727_websize.jpg",
        "caption": "Wedding & Reception-727_websize"
      },
      {
        "src": "photos/couple/I&A Wedding & Reception-760_websize.jpg",
        "caption": "Wedding & Reception-760_websize"
      },
      {
        "src": "photos/couple/SAB09011_websize.jpg",
        "caption": "SAB09011_websize"
      }
    ]
  },
  {
    "id": "decor",
    "name": "Decor",
    "photos": [
      {
        "src": "photos/decor/I&A Haldi-1_websize.jpg",
        "caption": "Haldi-1_websize"
      },
      {
        "src": "photos/decor/I&A Haldi-2_websize.jpg",
        "caption": "Haldi-2_websize"
      },
      {
        "src": "photos/decor/I&A Haldi-5_websize.jpg",
        "caption": "Haldi-5_websize"
      },
      {
        "src": "photos/decor/I&A Haldi-6_websize.jpg",
        "caption": "Haldi-6_websize"
      },
      {
        "src": "photos/decor/I&A Haldi-23_websize.jpg",
        "caption": "Haldi-23_websize"
      },
      {
        "src": "photos/decor/I&A Sangeet-18_websize.jpg",
        "caption": "Sangeet-18_websize"
      },
      {
        "src": "photos/decor/I&A Sangeet-19_websize.jpg",
        "caption": "Sangeet-19_websize"
      },
      {
        "src": "photos/decor/I&A Sangeet-26_websize.jpg",
        "caption": "Sangeet-26_websize"
      },
      {
        "src": "photos/decor/I&A Sangeet-47_websize.jpg",
        "caption": "Sangeet-47_websize"
      },
      {
        "src": "photos/decor/I&A Wedding & Reception-9_websize.jpg",
        "caption": "Wedding & Reception-9_websize"
      },
      {
        "src": "photos/decor/I&A Wedding & Reception-16_websize.jpg",
        "caption": "Wedding & Reception-16_websize"
      },
      {
        "src": "photos/decor/I&A Wedding & Reception-28_websize.jpg",
        "caption": "Wedding & Reception-28_websize"
      },
      {
        "src": "photos/decor/I&A Wedding & Reception-29_websize.jpg",
        "caption": "Wedding & Reception-29_websize"
      },
      {
        "src": "photos/decor/I&A Wedding & Reception-46_websize.jpg",
        "caption": "Wedding & Reception-46_websize"
      },
      {
        "src": "photos/decor/I&A Wedding & Reception-48_websize.jpg",
        "caption": "Wedding & Reception-48_websize"
      },
      {
        "src": "photos/decor/I&A Wedding & Reception-672_websize.jpg",
        "caption": "Wedding & Reception-672_websize"
      },
      {
        "src": "photos/decor/I&A Wedding & Reception-679_websize.jpg",
        "caption": "Wedding & Reception-679_websize"
      },
      {
        "src": "photos/decor/I&A Wedding & Reception-680_websize.jpg",
        "caption": "Wedding & Reception-680_websize"
      },
      {
        "src": "photos/decor/I&A Wedding & Reception-689_websize.jpg",
        "caption": "Wedding & Reception-689_websize"
      }
    ]
  },
  {
    "id": "ishita",
    "name": "Ishita",
    "photos": [
      {
        "src": "photos/ishita/1TSK1616_websize.jpg",
        "caption": "1TSK1616_websize"
      },
      {
        "src": "photos/ishita/1TSK1840_websize.jpg",
        "caption": "1TSK1840_websize"
      },
      {
        "src": "photos/ishita/1TSK2774_websize.jpg",
        "caption": "1TSK2774_websize"
      },
      {
        "src": "photos/ishita/1TSK4764_websize.jpg",
        "caption": "1TSK4764_websize"
      },
      {
        "src": "photos/ishita/1TSK8377_websize.jpg",
        "caption": "1TSK8377_websize"
      },
      {
        "src": "photos/ishita/1TSK8633_websize.jpg",
        "caption": "1TSK8633_websize"
      },
      {
        "src": "photos/ishita/BBC01713_websize.jpg",
        "caption": "BBC01713_websize"
      },
      {
        "src": "photos/ishita/I&A Haldi-49_websize.jpg",
        "caption": "Haldi-49_websize"
      },
      {
        "src": "photos/ishita/I&A Haldi-203_websize.jpg",
        "caption": "Haldi-203_websize"
      },
      {
        "src": "photos/ishita/I&A Haldi-226_websize.jpg",
        "caption": "Haldi-226_websize"
      },
      {
        "src": "photos/ishita/I&A Haldi-256_websize.jpg",
        "caption": "Haldi-256_websize"
      },
      {
        "src": "photos/ishita/I&A Sangeet-243_websize.jpg",
        "caption": "Sangeet-243_websize"
      },
      {
        "src": "photos/ishita/I&A Sangeet-256_websize.jpg",
        "caption": "Sangeet-256_websize"
      },
      {
        "src": "photos/ishita/I&A Wedding & Reception-87_websize.jpg",
        "caption": "Wedding & Reception-87_websize"
      },
      {
        "src": "photos/ishita/I&A Wedding & Reception-188_websize.jpg",
        "caption": "Wedding & Reception-188_websize"
      },
      {
        "src": "photos/ishita/I&A Wedding & Reception-205_websize.jpg",
        "caption": "Wedding & Reception-205_websize"
      },
      {
        "src": "photos/ishita/I&A Wedding & Reception-264_websize.jpg",
        "caption": "Wedding & Reception-264_websize"
      },
      {
        "src": "photos/ishita/I&A Wedding & Reception-514_websize.jpg",
        "caption": "Wedding & Reception-514_websize"
      }
    ]
  },
  {
    "id": "mom_dad",
    "name": "Mom Dad",
    "photos": [
      {
        "src": "photos/mom_dad/1TSK1513_websize.jpg",
        "caption": "1TSK1513_websize"
      },
      {
        "src": "photos/mom_dad/1TSK1518_websize.jpg",
        "caption": "1TSK1518_websize"
      },
      {
        "src": "photos/mom_dad/1TSK1527_websize.jpg",
        "caption": "1TSK1527_websize"
      },
      {
        "src": "photos/mom_dad/1TSK4487_websize.jpg",
        "caption": "1TSK4487_websize"
      },
      {
        "src": "photos/mom_dad/1TSK4490_websize.jpg",
        "caption": "1TSK4490_websize"
      },
      {
        "src": "photos/mom_dad/1TSK9506_websize.jpg",
        "caption": "1TSK9506_websize"
      },
      {
        "src": "photos/mom_dad/1TSK9535_websize.jpg",
        "caption": "1TSK9535_websize"
      },
      {
        "src": "photos/mom_dad/BBC00278_websize.jpg",
        "caption": "BBC00278_websize"
      },
      {
        "src": "photos/mom_dad/BBC00283_websize.jpg",
        "caption": "BBC00283_websize"
      },
      {
        "src": "photos/mom_dad/BBC09901_websize.jpg",
        "caption": "BBC09901_websize"
      },
      {
        "src": "photos/mom_dad/BBC09903_websize.jpg",
        "caption": "BBC09903_websize"
      },
      {
        "src": "photos/mom_dad/I&A Sangeet-90.jpg",
        "caption": "Sangeet"
      },
      {
        "src": "photos/mom_dad/I&A Sangeet-207_websize.jpg",
        "caption": "Sangeet-207_websize"
      },
      {
        "src": "photos/mom_dad/I&A Wedding & Reception-450_websize.jpg",
        "caption": "Wedding & Reception-450_websize"
      },
      {
        "src": "photos/mom_dad/SAB08044_websize.jpg",
        "caption": "SAB08044_websize"
      },
      {
        "src": "photos/mom_dad/SAB08048_websize.jpg",
        "caption": "SAB08048_websize"
      }
    ]
  },
  {
    "id": "sisters",
    "name": "Sisters",
    "photos": [
      {
        "src": "photos/sisters/I&A Haldi-45_websize.jpg",
        "caption": "Haldi-45_websize"
      },
      {
        "src": "photos/sisters/I&A Haldi-382_websize.jpg",
        "caption": "Haldi-382_websize"
      },
      {
        "src": "photos/sisters/I&A Wedding & Reception-88_websize.jpg",
        "caption": "Wedding & Reception-88_websize"
      },
      {
        "src": "photos/sisters/I&A Wedding & Reception-92_websize.jpg",
        "caption": "Wedding & Reception-92_websize"
      },
      {
        "src": "photos/sisters/I&A Wedding & Reception-94_websize.jpg",
        "caption": "Wedding & Reception-94_websize"
      },
      {
        "src": "photos/sisters/I&A Wedding & Reception-97_websize.jpg",
        "caption": "Wedding & Reception-97_websize"
      },
      {
        "src": "photos/sisters/I&A Wedding & Reception-326_websize.jpg",
        "caption": "Wedding & Reception-326_websize"
      },
      {
        "src": "photos/sisters/I&A Wedding & Reception-873_websize.jpg",
        "caption": "Wedding & Reception-873_websize"
      },
      {
        "src": "photos/sisters/I&A Wedding & Reception-874_websize.jpg",
        "caption": "Wedding & Reception-874_websize"
      },
      {
        "src": "photos/sisters/I&A Wedding & Reception-875_websize.jpg",
        "caption": "Wedding & Reception-875_websize"
      }
    ]
  }
];
