#!/usr/bin/env node
/**
 * build-photos.js
 *
 * Run from the folder that contains index.html:   node build-photos.js
 *
 * Step 1 (needs `npm install sharp`, otherwise skipped):
 *   For every folder next to index.html that directly contains images
 *   (e.g. highlight/, anushka/), make a web-sized copy in photos/<folder>/
 *   if one doesn't exist yet. Existing web copies are never overwritten.
 *
 * Step 2 (no installs needed):
 *   Scan photos/ and write js/photos-data.js, which defines the `highlights`
 *   and `people` arrays used by js/app.js.
 *     - photos/highlight/  -> carousel
 *     - every other folder in photos/ -> one person in the People section
 */

const fs = require("fs");
const path = require("path");

// ---------- Settings (edit if your layout differs) ----------
const ROOT = __dirname; // folder that contains index.html
const WEB_DIR = "photos"; // web-sized copies live here
const HIGHLIGHT_FOLDER = "highlight"; // name of the carousel folder
const OUTPUT_FILE = path.join("js", "photos-data.js");
const MAX_EDGE = 1800; // longest side in px for web copies
const QUALITY = 82; // JPEG/WebP quality
const IMAGE_EXT = /\.(jpe?g|png|webp)$/i;
const SKIP_DIRS = new Set([WEB_DIR, "node_modules", "css", "js"]);
// ------------------------------------------------------------

const natural = (a, b) =>
  a.localeCompare(b, undefined, { numeric: true, sensitivity: "base" });

function listDirs(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory() && !d.name.startsWith("."))
    .map((d) => d.name)
    .sort(natural);
}

function listImages(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((f) => f.isFile() && !f.name.startsWith(".") && IMAGE_EXT.test(f.name))
    .map((f) => f.name)
    .sort(natural);
}

// "I&A Wedding & Reception-97.jpg" -> "Wedding & Reception"
function captionFrom(file, fallback) {
  const cleaned = path
    .parse(file)
    .name.replace(/^I&A\s+/i, "")
    .replace(/[-_\s]*\d+$/, "")
    .trim();
  return cleaned || fallback;
}

// "anushka" -> "Anushka", "aunt-meera" -> "Aunt Meera"
function prettyName(folder) {
  return folder
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

async function makeWebCopies() {
  let sharp;
  try {
    sharp = require("sharp");
  } catch {
    console.log("• sharp not installed, skipping resize step (run: npm install sharp)");
    return;
  }

  let made = 0;
  for (const folder of listDirs(ROOT).filter((d) => !SKIP_DIRS.has(d))) {
    const srcDir = path.join(ROOT, folder);
    const images = listImages(srcDir);
    if (!images.length) continue;

    const outDir = path.join(ROOT, WEB_DIR, folder);
    fs.mkdirSync(outDir, { recursive: true });

    for (const file of images) {
      const out = path.join(outDir, file);
      if (fs.existsSync(out)) continue;

      let img = sharp(path.join(srcDir, file))
        .rotate() // respect camera EXIF orientation
        .resize({ width: MAX_EDGE, height: MAX_EDGE, fit: "inside", withoutEnlargement: true });

      const ext = path.extname(file).toLowerCase();
      if (ext === ".png") img = img.png({ compressionLevel: 9 });
      else if (ext === ".webp") img = img.webp({ quality: QUALITY });
      else img = img.jpeg({ quality: QUALITY, mozjpeg: true });

      await img.toFile(out);
      console.log(`  + ${WEB_DIR}/${folder}/${file}`);
      made++;
    }
  }
  console.log(`• Web copies created: ${made}`);
}

function buildManifest() {
  const webRoot = path.join(ROOT, WEB_DIR);
  const entry = (folder) => (file) => ({
    src: `${WEB_DIR}/${folder}/${file}`,
    caption: captionFrom(file, prettyName(folder)),
  });

  const highlights = listImages(path.join(webRoot, HIGHLIGHT_FOLDER)).map(entry(HIGHLIGHT_FOLDER));

  const people = listDirs(webRoot)
    .filter((folder) => folder !== HIGHLIGHT_FOLDER)
    .map((folder) => ({
      id: folder,
      name: prettyName(folder),
      photos: listImages(path.join(webRoot, folder)).map(entry(folder)),
    }))
    .filter((person) => person.photos.length > 0);

  const contents =
    "// AUTO-GENERATED by build-photos.js. Do not edit by hand; re-run the script instead.\n" +
    `const highlights = ${JSON.stringify(highlights, null, 2)};\n\n` +
    `const people = ${JSON.stringify(people, null, 2)};\n`;

  const outPath = path.join(ROOT, OUTPUT_FILE);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, contents);

  console.log(`• Wrote ${OUTPUT_FILE}`);
  console.log(`    highlights: ${highlights.length} photos`);
  people.forEach((p) => console.log(`    ${p.name}: ${p.photos.length} photos`));
}

(async () => {
  await makeWebCopies();
  buildManifest();
})().catch((err) => {
  console.error(err);
  process.exit(1);
});